---
title: "chordDiagram"
author: "SeuljiMoon"
date: "2023-08-18"
output: 
  html_document: 
    toc: yes
---

chordDiagram 을 위한 package 설치

```{r echo=T , message=F}
rm(list=ls())
if(!require("arules")) install.packages("arules")
if(!require("arulesViz")) install.packages("arules")
if(!require("visNetwork")) install.packages("visNetwork")
if(!require("igraph")) install.packages("igraph")
if(!require("circlize")) install.packages("circlize")
if(!require("RColorBrewer")) install.packages("RColorBrewer")
```

library setup
```{r library}
library(arules)
library(arulesViz)
library(visNetwork)
library(igraph) 
library(circlize) 
library(RColorBrewer) 
library(data.table); library(dplyr); library(tidyr)
```

Read dataset
```{r read dataset}
wide_raw <- fread("") #Private data

head(wide_raw)
```

Split dataset
comorbidities status 2-years after multiple myeloma diagnosis

```{r split dataset}
sm.names<-c("mi_yes", "pvd_yes", "cd_yes", "dem_yes", "hp_yes"
            ,"im_yes", "cpd_yes", "chf_yes", "pud_yes", "mld_yes"
            , "rd_yes", "dia_yes", "cancer_yes", "aids_yes")

cci.names <- c("MI", "PVD", "CVD", "Dementia", "Plegia", "IM",
               "CPD", "CHF", "PUD", "Liver",
               "RD","Diabetes", "Cancer", "AIDS")

wide_raw_after <- wide_raw %>% select(INDI_DSCM_NO, c90_yn, sex, age, ageg4, insu_g2
                                      , paste0(sm.names)
                                      , death, surv_years)
```


wide to long
```{r wide to long form}
long_raw_after <- wide_raw_after %>% 
  gather(key="key", value="value", paste0(sm.names)) %>% 
  separate(key, sep = '[_]', into = c('var','time')) %>% 
  arrange(INDI_DSCM_NO)

head(long_raw_after)
```

```{r case control dataset}
casedf <- long_raw_after |>
  dplyr::select(INDI_DSCM_NO , c90_yn, var, value) |> 
  filter(value == 1 & c90_yn ==1) |> 
  mutate(comorbity = case_when (var == 'aids' ~ 'AIDS', 
                                var == 'cancer' ~ 'Cancer', 
                                var == 'cd' ~ 'CVD',
                                var == 'chf' ~ 'CHF',
                                var == 'cpd' ~ ' CPD',
                                var == 'dem' ~ 'Dementia',
                                var == 'dia' ~ 'Diabetes',
                                var == 'hp' ~ 'Plegia',
                                var == 'im' ~ 'IM',
                                var == 'mi' ~ 'MI',
                                var == 'mld' ~ 'Liver',
                                var == 'pud' ~ 'PUD',
                                var == 'pvd' ~ 'PVD',
                                var == 'rd' ~ 'RD'))


controldf <- long_raw_after |>
  dplyr::select(INDI_DSCM_NO , c90_yn, var, value) |> 
  filter(value == 1 & c90_yn ==0) |> 
  mutate(comorbity = case_when (var == 'aids' ~ 'AIDS', 
                                var == 'cancer' ~ 'Cancer', 
                                var == 'cd' ~ 'CVD',
                                var == 'chf' ~ 'CHF',
                                var == 'cpd' ~ ' CPD',
                                var == 'dem' ~ 'Dementia',
                                var == 'dia' ~ 'Diabetes',
                                var == 'hp' ~ 'Plegia',
                                var == 'im' ~ 'IM',
                                var == 'mi' ~ 'MI',
                                var == 'mld' ~ 'Liver',
                                var == 'pud' ~ 'PUD',
                                var == 'pvd' ~ 'PVD',
                                var == 'rd' ~ 'RD'))
```

make matrix
```{r matrix}
case_cross <- crossprod(table(casedf[c(1,5)]))
control_cross <- crossprod(table(controldf[c(1,5)]))

diag(case_cross) <- 0 
diag(control_cross) <- 0
```

Draw chordDiagram - Multiple myeloma patients and Controls
```{r case chordDiagram}
nb.cols <- 14
mycolors <- colorRampPalette(brewer.pal(12, "Paired"))(nb.cols)

par(mfrow = c(1, 2))

chordDiagram(case_cross, annotationTrack = "grid", preAllocateTracks = list(track.height = 0.1), 
             grid.col = mycolors)
title(main = "Multiple Myeloma")
circos.trackPlotRegion(track.index = 1, panel.fun = function(x, y) {
  xlim = get.cell.meta.data("xlim")
  xplot = get.cell.meta.data("xplot")
  ylim = get.cell.meta.data("ylim")
  sector.name = get.cell.meta.data("sector.index")
  if(abs(xplot[2] - xplot[1]) < 10) {
    circos.text(mean(xlim), ylim[1], sector.name, facing = "clockwise",
                niceFacing = TRUE, adj = c(0, 0.5))
  } else {
    circos.text(mean(xlim), ylim[1], sector.name, facing = "inside",
                niceFacing = TRUE, adj = c(0.5, 0))
  }
}, bg.border = NA)


chordDiagram(control_cross, annotationTrack = "grid", preAllocateTracks = list(track.height = 0.1), 
             grid.col = mycolors)
title(main = "Control")
circos.trackPlotRegion(track.index = 1, panel.fun = function(x, y) {
  xlim = get.cell.meta.data("xlim")
  xplot = get.cell.meta.data("xplot")
  ylim = get.cell.meta.data("ylim")
  sector.name = get.cell.meta.data("sector.index")
  if(abs(xplot[2] - xplot[1]) < 10) {
    circos.text(mean(xlim), ylim[1], sector.name, facing = "clockwise",
                niceFacing = TRUE, adj = c(0, 0.5))
  } else {
    circos.text(mean(xlim), ylim[1], sector.name, facing = "inside",
                niceFacing = TRUE, adj = c(0.5, 0))
  }
}, bg.border = NA)

```

